import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import App from '../App'

function view(path = '/') { return render(<MemoryRouter initialEntries={[path]}><App/></MemoryRouter>) }
describe('Clare Connects website', () => {
  test('renders the owner-approved homepage welcome and navigation', () => { view(); expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('Welcome to Clare Connects'); expect(screen.getByRole('navigation', { name: 'Main navigation' })).toHaveTextContent('Join the Team') })
  test('renders Clare’s approved logo and photography', () => { view(); expect(screen.getByAltText('Clare, founder of Clare Connects')).toHaveAttribute('src', '/assets/clare-headshot-studio.jpg'); expect(screen.getAllByRole('link', { name: 'Clare Connects home' })[0].querySelector('img')).toHaveAttribute('src', '/assets/clare-connects-logo.png') })
  test('routes to business utilities', () => { view('/business-utilities'); expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('Bring clarity') })
  test('routes the utilities shortcut to household utilities', async () => { view('/utilities'); await waitFor(() => expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('One conversation')) })
  test('renders supplied Connector and opportunity links', () => { view('/connectors'); expect(screen.getByRole('link', { name: /Register as a Connector/ })).toHaveAttribute('href', 'https://uw.partners/clare.and.john/connect'); expect(screen.getAllByRole('link', { name: /Watch how it works/ })[0]).toHaveAttribute('href', 'https://vimeo.com/1200796333') })
  test('embeds the Connector explainer video', () => { view('/connectors'); expect(screen.getByTitle('How Clare Connectors work')).toHaveAttribute('src', 'https://player.vimeo.com/video/1200796333') })
  test('uses the correct personalised UW links', () => { const join = view('/join'); expect(screen.getByRole('link', { name: /Visit Clare’s Join page/ })).toHaveAttribute('href', 'https://uw.partners/clare.and.john/join'); join.unmount(); view('/home-utilities'); expect(screen.getByRole('link', { name: /Visit Clare’s UW homepage/ })).toHaveAttribute('href', 'https://uw.partners/clare.and.john') })
  test('shows the inclusive team artwork and business planning guidance', () => { const join = view('/join'); expect(screen.getByAltText(/happy, inclusive team/)).toHaveAttribute('src', '/assets/clare-connects-team.png'); join.unmount(); view('/business-utilities'); expect(screen.getByText('Did you know?')).toBeInTheDocument(); expect(screen.getByText(/as much as a year before/)).toBeInTheDocument() })
  test('shows branded not found page', () => { view('/missing-page'); expect(screen.getByText('This page isn’t part of the network.')).toBeInTheDocument() })
  test('opens and closes the mobile menu accessibly', async () => { const user = userEvent.setup(); view(); await user.click(screen.getByRole('button', { name: 'Open menu' })); expect(screen.getByRole('dialog', { name: 'Navigation menu' })).toBeInTheDocument(); await user.keyboard('{Escape}'); expect(screen.queryByRole('dialog', { name: 'Navigation menu' })).not.toBeInTheDocument() })
  test('validates required contact form fields', async () => { const user = userEvent.setup(); view('/contact'); await user.click(screen.getByRole('button', { name: 'Send enquiry' })); expect(screen.getByRole('alert')).toHaveTextContent('Please enter your name'); expect(screen.getByRole('alert')).toHaveTextContent('valid email') })
  test('submits the contact form and announces success', async () => { const user = userEvent.setup(); view('/contact'); await user.type(screen.getByLabelText(/Name/), 'John'); await user.type(screen.getByLabelText(/Email/), 'john@example.com'); await user.type(screen.getByLabelText(/Message/), 'Please contact me about my home services.'); await user.click(screen.getByRole('checkbox')); await user.click(screen.getByRole('button', { name: 'Send enquiry' })); await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('Thank you'), { timeout: 2000 }) })
  test('opens, resets and closes the assistant', async () => { const user = userEvent.setup(); view(); await user.click(screen.getByRole('button', { name: 'Open Ask Clare Connects assistant' })); expect(screen.getByRole('dialog', { name: 'Ask Clare Connects' })).toBeInTheDocument(); await user.click(screen.getByRole('button', { name: 'Reset' })); await user.click(screen.getByRole('button', { name: 'Close assistant' })); expect(screen.queryByRole('dialog', { name: 'Ask Clare Connects' })).not.toBeInTheDocument() })
})
