import { ArrowUpRight, BriefcaseBusiness, Check, HeartHandshake, Network, Share2, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { ContactForm } from '../components/ContactForm'
import { PageHero, SectionHead, Steps } from '../components/Elements'

export function Connectors() { return <>
  <PageHero eyebrow="Clare Connectors" title={<>Good connections create <em>better opportunities.</em></>} intro="Become part of a relationship-led network that brings Clare Connects together with people and organisations who may genuinely benefit."><Link className="button" to="#connector-enquiry" onClick={() => setTimeout(() => document.getElementById('connector-enquiry')?.scrollIntoView({ behavior: 'smooth' }), 0)}>Explore becoming a Connector <ArrowUpRight /></Link></PageHero>
  <section className="section connector-definition"><div className="connector-symbol"><Network /><span>People</span><span>Clare</span><span>Business</span></div><div><span className="eyebrow">What is a Clare Connector?</span><h2>A trusted introduction, made with purpose.</h2><p>A Connector is someone who introduces Clare to a household, organisation or professional contact who may benefit from her help. It can be as simple as a thoughtful recommendation or form part of a wider professional collaboration.</p><p>The focus is always on relevance and trust. Connectors do not need to quote, advise or sell services on Clare’s behalf.</p></div></section>
  <section className="section cream"><SectionHead eyebrow="A network with many shapes" title="Who could become a Connector?" centre /><div className="connector-types">{[[BriefcaseBusiness,'Professional advisers','Accountants, consultants, coaches and property professionals.'],[Users,'Community connectors','Local leaders, networking members and people with strong relationships.'],[HeartHandshake,'Customers & advocates','People who know Clare’s approach and feel comfortable recommending her.']].map(([Icon,title,text])=>{const I=Icon as typeof Users; return <article key={String(title)}><I/><h3>{String(title)}</h3><p>{String(text)}</p></article>})}</div><p className="audience-line">Accountants · Business coaches · Commercial landlords · Community leaders · Consultants · Existing customers</p></section>
  <section className="section"><SectionHead eyebrow="How introductions work" title="Straightforward from the first hello." /><Steps items={[{title:'Spot a useful connection',text:'Someone mentions a need that fits Clare’s household, business or opportunity services.'},{title:'Ask permission',text:'Check that they are happy to be introduced. A warm introduction should never be a surprise.'},{title:'Connect them with Clare',text:'Share Clare’s details or make a direct introduction with everyone’s agreement.'},{title:'Clare takes it from there',text:'Clare listens, explains the available route and keeps any relevant parties appropriately informed.'}]}/></section>
  <section className="section plum connector-benefits"><div><span className="eyebrow">Part of something useful</span><h2>Connections built on <em>care and credibility.</em></h2></div><div className="benefit-list"><p><Check/> Help people find a clear next step</p><p><Check/> Strengthen trusted professional relationships</p><p><Check/> Collaborate across Clare’s wider network</p><p><Check/> Keep the arrangement personal and transparent</p></div><aside><Share2/><p>Exact commercial arrangements are discussed personally and may depend on the service involved. No commission rate or reward is promised by this website.</p></aside></section>
  <section className="section form-section" id="connector-enquiry"><div className="form-intro"><span className="eyebrow">Start a connector conversation</span><h2>Who might you help Clare connect with?</h2><p>Share a little about you and the kinds of introductions you may be able to make. Clare will come back to you personally.</p></div><ContactForm kind="connector" /></section>
  </> }
