import { ArrowUpRight, BriefcaseBusiness, Building2, Check, CirclePlay, Gift, HeartHandshake, Network, Share2, Users } from 'lucide-react'
import { ContactForm } from '../components/ContactForm'
import { PageHero, SectionHead, Steps } from '../components/Elements'
import { site } from '../content/siteContent'

export function Connectors() { return <>
  <PageHero eyebrow="Clare Connectors" title={<>Good connections create <em>better opportunities.</em></>} intro="Become part of a relationship-led network that brings Clare Connects together with people and organisations who may genuinely benefit."><div className="button-row"><a className="button" href={site.links.connectorRegistration} target="_blank" rel="noreferrer">Register as a Connector <ArrowUpRight /></a><a className="button button-quiet" href={site.links.connectorExplainer} target="_blank" rel="noreferrer"><CirclePlay /> Watch how it works</a></div></PageHero>
  <section className="section connector-definition"><div className="connector-symbol"><Network /><span>People</span><span>Clare</span><span>Business</span></div><div><span className="eyebrow">What is a Clare Connector?</span><h2>A trusted introduction, made with purpose.</h2><p>A Connector is someone who introduces Clare to a household, organisation or professional contact who may benefit from her help. It can be as simple as a thoughtful recommendation or form part of a wider professional collaboration.</p><p>The focus is always on relevance and trust. Connectors do not need to quote, advise or sell services on Clare’s behalf.</p></div></section>
  <section className="section cream"><SectionHead eyebrow="A network with many shapes" title="Who could become a Connector?" centre /><div className="connector-types">{[[BriefcaseBusiness,'Professional advisers','Accountants, consultants, coaches and property professionals.'],[Users,'Community connectors','Local leaders, networking members and people with strong relationships.'],[HeartHandshake,'Customers & advocates','People who know Clare’s approach and feel comfortable recommending her.']].map(([Icon,title,text])=>{const I=Icon as typeof Users; return <article key={String(title)}><I/><h3>{String(title)}</h3><p>{String(text)}</p></article>})}</div><p className="audience-line">Accountants · Business coaches · Commercial landlords · Community leaders · Consultants · Existing customers</p></section>
  <section className="section"><SectionHead eyebrow="How introductions work" title="Straightforward from the first hello." /><Steps items={[{title:'Spot a useful connection',text:'Someone mentions a need that fits Clare’s household, business or opportunity services.'},{title:'Ask permission',text:'Check that they are happy to be introduced. A warm introduction should never be a surprise.'},{title:'Connect them with Clare',text:'Share Clare’s details or make a direct introduction with everyone’s agreement.'},{title:'Clare takes it from there',text:'Clare listens, explains the available route and keeps any relevant parties appropriately informed.'}]}/></section>
  <section className="section cream connector-video"><SectionHead eyebrow="Watch the Connector explainer" title={<>See how a thoughtful introduction <em>can make a difference.</em></>} intro="This short video explains how Connectors work and how you can get involved." /><div className="video-frame"><iframe src="https://player.vimeo.com/video/1200796333" title="How Clare Connectors work" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen loading="lazy" /></div></section>
  <section className="section plum connector-benefits"><div><span className="eyebrow">Part of something useful</span><h2>Connections built on <em>care and credibility.</em></h2></div><div className="benefit-list"><p><Check/> Help people find a clear next step</p><p><Check/> Strengthen trusted professional relationships</p><p><Check/> Collaborate across Clare’s wider network</p><p><Check/> Keep the arrangement personal and transparent</p></div><aside><Share2/><p>Exact commercial arrangements are discussed personally and may depend on the service involved. No commission rate or reward is promised by this website.</p></aside></section>
  <section className="section connector-rewards"><SectionHead eyebrow="Spread the word" title={<>Introductions can support <em>goals that matter.</em></>} intro="Subject to the current programme terms and a successful eligible introduction, Connector rewards may provide a useful contribution towards personal, business or community goals." centre /><div className="reward-grid"><article><Building2/><h3>Your business</h3><p>A possible additional contribution for a business built around trusted local relationships.</p></article><article><Gift/><h3>Your personal plans</h3><p>Put eligible rewards towards something meaningful to you, such as a future holiday or family goal.</p></article><article><HeartHandshake/><h3>Your community</h3><p>Explore whether introductions could support a club, community group or charity you care about.</p></article></div><div className="connector-actions"><p>Rewards are not guaranteed. Eligibility, value and payment depend on the service involved and the applicable programme terms, which are provided during registration.</p><div className="button-row"><a className="button" href={site.links.connectorRegistration} target="_blank" rel="noreferrer">Register a new Connector <ArrowUpRight /></a><a className="text-link" href={site.links.connectorExplainer} target="_blank" rel="noreferrer"><CirclePlay /> Watch the Connector explainer</a></div></div></section>
  <section className="section form-section" id="connector-enquiry"><div className="form-intro"><span className="eyebrow">Start a connector conversation</span><h2>Who might you help Clare connect with?</h2><p>Share a little about you and the kinds of introductions you may be able to make. Clare will come back to you personally.</p></div><ContactForm kind="connector" /></section>
  </> }
