import { ArrowRight, ArrowUpRight, Check, HeartHandshake, Network, ShieldCheck, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CTA, IconBox, SectionHead, SplitFeature, Steps } from '../components/Elements'
import { site, testimonials } from '../content/siteContent'

export function Home() {
  return <>
    <section className="home-hero"><div className="hero-lines" aria-hidden="true"><i /><i /><i /><span>✦</span></div><div className="home-hero-copy"><span className="eyebrow"><Sparkles /> Home, business & opportunity</span><h1>Connections that make <em>life and business</em> simpler.</h1><p>One trusted point of contact for essential services, cost-conscious conversations and useful introductions, all with a personal touch.</p><div className="button-row"><Link className="button" to="/home-utilities">Discover how Clare can help <ArrowUpRight /></Link><Link className="button button-quiet" to="/contact">Talk to Clare <ArrowRight /></Link></div><div className="hero-note"><span><ShieldCheck /> Established providers</span><span><HeartHandshake /> Personal support</span></div></div>
      <div className="hero-portrait"><div className="portrait-frame"><img src={site.portrait} alt="Clare, founder of Clare Connects" /><span className="portrait-note">Your trusted point of contact</span></div><div className="floating-card"><Network /><div><strong>Everything connects</strong><span>Home · Business · Opportunity</span></div></div></div>
    </section>
    <section className="pathways section"><SectionHead eyebrow="Start with what matters" title={<>Three ways to <em>connect</em></>} intro="Whether you are reviewing home essentials, simplifying business services or exploring something new, Clare makes the next step feel clear." />
      <div className="path-grid"><Path number="01" title="Home Utilities" text="Bring energy, broadband, mobile and other household essentials into one helpful conversation." to="/home-utilities" className="home-path" /><Path number="02" title="Business Utilities" text="Make renewal dates, essential services and specialist introductions easier to navigate." to="/business-utilities" className="business-path" /><Path number="03" title="Join the Opportunity" text="Explore a flexible, relationship-led way to build something gradually with Clare’s support." to="/join" className="join-path" /></div>
    </section>
    <section className="section cream"><SplitFeature visual="portrait" image={site.portraitWarm} imageAlt="Clare smiling"><span className="eyebrow">Meet Clare</span><h2>A knowledgeable guide, <em>not a call centre.</em></h2><p>Clare Connects grew from a simple belief: important decisions feel easier when there is a real person who listens, explains and stays involved.</p><p>Clare helps households and organisations explore suitable services through established providers and trusted specialists. You get clear next steps and a familiar point of contact along the way.</p><Link className="text-link" to="/contact">Start a conversation with Clare <ArrowUpRight /></Link></SplitFeature></section>
    <section className="section reasons"><SectionHead eyebrow="Why Clare Connects" title={<>A more personal way to <em>move forward</em></>} centre /><div className="reason-grid">{[
      ['HeartHandshake', 'One trusted contact', 'A real person who takes time to understand what you need.'], ['Sparkles', 'Straightforward help', 'Clear conversations without pressure, jargon or unnecessary complexity.'], ['Network', 'A connected network', 'Access to established providers and relevant specialists through Clare.'], ['House', 'Home and business', 'Practical support across household and organisational essentials.'], ['RefreshCw', 'Ongoing support', 'A relationship that can continue beyond one decision or renewal.'],
    ].map(([icon, title, text]) => <article key={title}><IconBox name={icon} /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="section plum how"><div><SectionHead eyebrow="How it works" title={<>Useful next steps, <em>beautifully simple.</em></>} intro="No hard sell. Just a calm, practical process shaped around you." /><Link className="button button-gold" to="/contact">Begin with a hello <ArrowUpRight /></Link></div><Steps items={[{ title: 'Start a conversation', text: 'Share what is changing, what feels complicated or what you would like to review.' }, { title: 'Clare listens', text: 'Your priorities, timings and current setup help shape the conversation.' }, { title: 'Explore suitable options', text: 'Clare works through the relevant choices and trusted introductions.' }, { title: 'Receive clear next steps', text: 'You decide what feels right, with Clare remaining your point of contact.' }]} /></section>
    <section className="section connectors-preview"><div className="connector-art"><span>Connections</span><div className="nodes"><i /><i /><i /><i /></div></div><div><span className="eyebrow">Clare Connectors</span><h2>Good connections create <em>better opportunities.</em></h2><p>Clare Connectors is a welcoming network for people who make thoughtful introductions. You might recommend Clare informally or collaborate as a trusted professional connector.</p><ul className="check-list"><li><Check /> Make genuinely useful introductions</li><li><Check /> Strengthen local relationships</li><li><Check /> Stay connected to Clare’s support</li></ul><Link className="text-link" to="/connectors">Discover Clare Connectors <ArrowUpRight /></Link></div></section>
    <section className="section testimonial-section"><SectionHead eyebrow="Stories that matter" title="Built on trust, shared with care." intro="Approved customer stories will be added here with permission. These placeholders show how the finished testimonials will feel." centre /><div className="testimonials">{testimonials.map((item) => <figure key={item.label}><Sparkles /><blockquote>“{item.quote}”</blockquote><figcaption>{item.label}</figcaption></figure>)}</div></section>
    <CTA />
  </>
}
function Path({ number, title, text, to, className }: { number: string; title: string; text: string; to: string; className: string }) { return <Link to={to} className={`path-card ${className}`}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div><ArrowUpRight /></Link> }
