import { ArrowUpRight, Check, Clock, Heart, MessageCircle, Sprout, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CTA, Faqs, PageHero, SectionHead, Steps } from '../components/Elements'
import { faqs, site } from '../content/siteContent'

export function Join() { return <>
  <PageHero tone="dark" eyebrow="Explore the opportunity" title={<>Build connections. Develop confidence. <em>Grow at your pace.</em></>} intro="A flexible, relationship-led opportunity for people who enjoy helping others and want to build something gradually with Clare’s support."><div className="button-row"><a className="button button-gold" href={site.links.opportunity} target="_blank" rel="noreferrer">View Clare’s opportunity page <ArrowUpRight /></a><Link className="button button-dark-quiet" to="/contact">Talk to Clare first</Link></div></PageHero>
  <section className="section opportunity-intro"><div className="quote-mark">“</div><div><span className="eyebrow">An honest starting point</span><h2>A conversation about what could fit your life.</h2><p>This is not a promise of effortless income. It is an invitation to explore a people-focused opportunity where listening, consistency and personal effort matter.</p></div><div className="opportunity-note"><Sprout/><p>You can begin with a conversation, ask questions and decide whether the approach feels right for you.</p></div></section>
  <section className="section cream"><SectionHead eyebrow="Who it may suit" title="For people who enjoy making things happen." centre /><div className="suit-grid">{[[Heart,'Natural helpers','You like finding useful solutions and seeing others move forward.'],[MessageCircle,'Relationship builders','You listen well, communicate clearly and build trust over time.'],[Clock,'Flexibility seekers','You want something that can develop around existing commitments.'],[Users,'Connected business owners','You see value in complementary services and wider relationships.']].map(([Icon,title,text])=>{const I=Icon as typeof Heart;return <article key={String(title)}><I/><h3>{String(title)}</h3><p>{String(text)}</p></article>})}</div></section>
  <section className="section learning"><div><SectionHead eyebrow="What you could develop" title={<>Practical skills with <em>lasting value.</em></>} intro="The experience can help you strengthen skills that matter in many parts of work and life."/><ul className="check-list"><li><Check/> Starting confident, natural conversations</li><li><Check/> Understanding needs before suggesting next steps</li><li><Check/> Building and caring for a customer base</li><li><Check/> Following up with consistency and respect</li></ul></div><div className="learning-card"><span>Support</span><h3>You are not expected to know everything on day one.</h3><p>Clare can explain the approach, answer questions and help you understand the support and community around the opportunity.</p></div></section>
  <section className="section plum"><SectionHead eyebrow="Your first conversation" title="Open, practical and without pressure." centre/><Steps items={[{title:'Your reasons',text:'What you hope to build, learn or change.'},{title:'Your circumstances',text:'The time, commitments and relationships you are working around.'},{title:'The approach',text:'What the opportunity involves and what consistent effort can look like.'},{title:'Your questions',text:'Space to understand programme terms and decide whether to continue.'}]}/></section>
  <section className="section disclaimer"><strong>Important to know</strong><p>Outcomes vary and depend on individual effort, circumstances, customers and applicable programme terms. No income or result is guaranteed. Clare will discuss the current programme details with you personally before you make a decision.</p></section>
  <section className="section faq-section"><SectionHead eyebrow="Opportunity FAQs" title="Ask the questions that matter."/><Faqs items={faqs.join}/></section><CTA title="Curious enough for a conversation?" text="Tell Clare what interests you and what you would like the opportunity to fit around." label="Explore the opportunity"/>
  </> }
