import { ArrowUpRight, Building2, Check, Clock3, FileSearch, HeartHandshake, Leaf, Store, Users } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CTA, Faqs, PageHero, SectionHead, ServiceGrid, SplitFeature, Steps } from '../components/Elements'
import { businessServices, faqs, homeServices, site } from '../content/siteContent'

export function HomeUtilities() { return <>
  <PageHero eyebrow="Household essentials, made simpler" title={<>One conversation. <em>More joined-up options.</em></>} intro="Clare can help you compare and arrange essential household services through established providers, with personal support from start to finish."><div className="button-row"><Link className="button" to="/contact">Review my household setup <ArrowUpRight /></Link><span className="hero-smallprint">Clare Connects is not a utility supplier.</span></div></PageHero>
  <section className="section intro-band"><div className="large-stat">One</div><div><span className="eyebrow">A refreshingly human approach</span><h2>One friendly conversation instead of several separate organisations.</h2><p>Your home services should support everyday life, not add to your to-do list. Clare takes time to understand what you use, what matters to you and which options may be worth exploring.</p></div></section>
  <section className="section"><SectionHead eyebrow="Services available through Clare" title={<>Bring your household <em>essentials together.</em></>} intro="Availability varies by location and provider. Clare will explain who supplies each service and what the next step involves." /><ServiceGrid items={homeServices} /></section>
  <section className="section cream"><SplitFeature><span className="eyebrow">A worthwhile review</span><h2>Could your household setup <em>work harder for you?</em></h2><p>Life changes, contracts end and habits shift. A calm review can reveal services that no longer fit, or simply give you confidence that your current setup still makes sense.</p><ul className="check-list"><li><Check /> Review several essentials together</li><li><Check /> Understand your options in plain English</li><li><Check /> Keep Clare as your point of contact</li></ul><Link className="button button-outline" to="/contact">Arrange a household conversation <ArrowUpRight /></Link></SplitFeature></section>
  <section className="section"><SectionHead eyebrow="Your household review" title="A clear route from question to next step." centre /><Steps items={[{ title: 'Tell Clare what you use', text: 'Share the services you would like to review and anything that has changed.' }, { title: 'Look at the whole picture', text: 'Clare considers your preferences, usage and practical priorities.' }, { title: 'Explore suitable options', text: 'Available choices are explained clearly, without absolute savings claims.' }, { title: 'Choose your next step', text: 'Clare helps you understand what happens next and stays in touch.' }]} /></section>
  <section className="section plum faq-section"><SectionHead eyebrow="Questions, answered" title="A little more clarity." /><Faqs items={faqs.home} /></section><section className="uw-home-link"><div><span className="eyebrow">Explore Utility Warehouse</span><h2>Visit Clare’s personalised UW homepage.</h2><p>See the household services currently available through Clare and Utility Warehouse.</p></div><a className="button button-gold" href={site.links.homeUtilities} target="_blank" rel="noreferrer">Visit Clare’s UW homepage <ArrowUpRight /></a></section><CTA title="Ready for a simpler household review?" label="Talk to Clare about home utilities" />
  </> }

export function BusinessUtilities() { return <>
  <PageHero tone="dark" eyebrow="Essential services for your organisation" title={<>Bring clarity to the <em>business behind your business.</em></>} intro="Clare coordinates cost, renewal and efficiency conversations across essential services, connecting you with established providers and trusted specialists."><div className="button-row"><Link className="button button-gold" to="/contact">Arrange a business review <ArrowUpRight /></Link><a className="button button-dark-quiet" href="mailto:clare@clareconnects.com">Email Clare</a></div></PageHero>
  <section className="section challenge"><div><span className="eyebrow">Less friction, more focus</span><h2>Multiple suppliers. Different renewal dates. <em>One point of contact.</em></h2></div><p>Keeping essential services organised can pull attention away from running your organisation. Clare helps bring the right conversations together, whether you are planning ahead, reviewing costs or exploring a specialist solution.</p></section>
  <section className="section"><SectionHead eyebrow="Connected business services" title={<>Practical support for the <em>way you operate.</em></>} intro="Clare coordinates and introduces these services through her network. The relevant provider remains responsible for supply, advice and installation." /><ServiceGrid items={businessServices} /></section>
  <section className="section cream"><SplitFeature visual="business"><span className="eyebrow">Cost and efficiency pathway</span><h2>Look beyond the next renewal.</h2><p>A useful review considers more than a headline rate. Contract timings, consumption, operational needs and future plans can all shape the right conversation.</p><ul className="check-list"><li><FileSearch /> Understand contracts and renewal dates</li><li><Leaf /> Explore efficiency and sustainability options</li><li><HeartHandshake /> Connect with the right specialist</li></ul><Link className="text-link" to="/contact">Discuss your organisation <ArrowUpRight /></Link></SplitFeature></section>
  <section className="section did-you-know"><div className="did-you-know-label"><span>Did you know?</span></div><div><h2>It is never too early to plan better business utilities.</h2><p>You may be able to begin exploring future savings as much as a year before your current contract ends, depending on your contract and the providers available. Planning ahead gives Clare more time to understand your needs and compare suitable options.</p><p>If you are taking over new premises, contracts held by the previous occupier will not normally transfer to you. Clare can help you review the available providers and look for an appropriate price and service for your new business address.</p><Link className="text-link" to="/contact">Plan ahead with Clare <ArrowUpRight /></Link></div></section>
  <section className="section audience"><SectionHead eyebrow="Who Clare can help" title="Support shaped around real organisations." centre /><div className="audience-grid">{[[Store,'Retail & hospitality'],[Building2,'Offices & SMEs'],[Users,'Community venues'],[Clock3,'Property businesses']].map(([Icon,label]) => { const I=Icon as typeof Store; return <div key={String(label)}><I /><span>{String(label)}</span></div> })}</div></section>
  <section className="section plum how"><div><SectionHead eyebrow="The consultation" title={<>A focused process with <em>room to think.</em></>} intro="A credible review begins with understanding your business, not pushing a product." /></div><Steps items={[{ title: 'Scope the review', text: 'Discuss services, sites, renewal dates and current priorities.' }, { title: 'Understand the detail', text: 'Gather the information relevant providers need to explore suitable choices.' }, { title: 'Coordinate options', text: 'Clare brings together provider conversations and trusted introductions.' }, { title: 'Agree next steps', text: 'You receive a clear route forward, without pressure or false guarantees.' }]} /></section>
  <section className="section faq-section"><SectionHead eyebrow="Business FAQs" title="Answers for decision-makers." /><Faqs items={faqs.business} /></section><CTA title="Make your next business review more joined up." text="Tell Clare which services, sites or renewals are on your mind." label="Arrange a business enquiry" />
  </> }
